[workspace]

members = [
    "math",
    "crypto",
    "prover",
]

[patch."https://github.com/maxgillett/winterfell"]
prover = { package = "winter-prover", path = "../maxgillet_winterfell/winterfell/prover", version = "0.4", features = ["concurrent"] }
crypto = { package = "winter-crypto", path = "../maxgillet_winterfell/winterfell/crypto", version = "0.4", features = ["concurrent"] }
math = { package = "winter-math", path = "../maxgillet_winterfell/winterfell/math", version = "0.4", features = ["concurrent"] }
winter-utils = { package = "winter-utils", path = "../maxgillet_winterfell/winterfell/utils/core" }
winter-air = { package = "winter-air", path = "../maxgillet_winterfell/winterfell/air", version = "0.4" }
winterfell = { package = "winter-verifier", path = "../maxgillet_winterfell/winterfell/verifier", version = "0.4" }
